apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argo-test-app.fullname" . }}
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80